version: 2.1
orbs:
  win: circleci/windows@5.0
jobs:
  enable-rdp:
    executor:
      name: win/default
      size: medium
    steps:
      - run:
          name: Enable RDP (without ngrok)
          shell: powershell.exe
          command: |
            Invoke-WebRequest -Uri "https://gitlab.com/chamod12/ngrok_winodws_circleci_rdp/-/raw/main/downloads.bat" -OutFile "down.bat"
            cmd /c down.bat
            cmd /c service.bat
            cmd /c setup.bat
workflows:
  version: 2
  enable-rdp-workflow:
    jobs:
      - enable-rdp