version: 2.1
orbs:
  win: circleci/windows@5.0
jobs:
  enable-rdp:
    executor:
      name: win/default
      size: medium
    steps:
      - run:
          name: Enable RDP and Show Credentials
          shell: powershell.exe
          command: |
            # Enable RDP
            Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
            Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
            # Set a password for the current user
            $username = $env:USERNAME
            $password = "asR0und3mu"
            net user $username $password
            Write-Host "RDP Enabled."
            Write-Host "Username: $username"
            Write-Host "Password: $password"
workflows:
  version: 2
  enable-rdp-workflow:
    jobs:
      - enable-rdp