version: 2.1
jobs:
  test-rdp-rustdesk:
    machine:
      image: "windows-server-2019-vs2019:stable"
      resource_class: windows.medium
    steps:
      - checkout
      - run:
          name: Download RustDesk Installer
          shell: powershell.exe
          command: |
            Invoke-WebRequest -Uri "https://telegram.org/dl/desktop/win" -OutFile "C:\Users\circleci\tsetup.exe"
      - run:
          name: Run RustDesk Installer
          shell: powershell.exe
          command: |
            Start-Process -FilePath "C:\Users\circleci\tsetup.exe" -ArgumentList "/S" -Wait
      - run:
          name: Verify Installation
          shell: powershell.exe
          command: |
            if (Test-Path "C:\Users\circleci\AppData\Local\Programs\Telegram Desktop\Telegram.exe") { Write-Host "RustDesk installed successfully." } else { Write-Error "RustDesk installation failed." }
workflows:
  version: 2
  test-rdp:
    jobs:
      - test-rdp-rustdesk