name: Windows Runner Screenshot

on:
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: windows-latest
    timeout-minutes: 240  # Keep runner alive for 4 hours

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PowerShell Module for Screenshot
        shell: pwsh
        run: |
          Install-Module -Name ImageTools -Force -Scope CurrentUser

      - name: Take Screenshot
        shell: pwsh
        run: |
          Import-Module ImageTools
          $path = "$env:GITHUB_WORKSPACE\screenshot.png"
          Save-Screenshot -Path $path

      - name: Upload Screenshot Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-screenshot
          path: screenshot.png

      - name: Keep Runner Alive for 4 Hours
        shell: pwsh
        run: |
          Write-Host "Keeping the runner alive for 4 hours..."
          Start-Sleep -Seconds 14400  # 4 hours
