name: WScreenshot with RustDesk

on:
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: windows-latest
    timeout-minutes: 240  # Keep runner alive for 4 hours

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download RustDesk
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/rustdesk/rustdesk/releases/download/1.4.0/rustdesk-1.4.0-x86_64.exe" -OutFile "$env:GITHUB_WORKSPACE\rustdesk.exe"

      - name: Prepare RustDesk config directory
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "$env:GITHUB_WORKSPACE\rustdesk-config"

      - name: Download RustDesk config artifact (optional)
        uses: actions/download-artifact@v4
        with:
          name: rustdesk-config
          path: rustdesk-config
        continue-on-error: true  # In case no config artifact exists yet

      - name: Start RustDesk with custom config (if supported)
        shell: pwsh
        run: |
          # If RustDesk supports --config argument, use it. If not, it will use the default location.
          Start-Process -FilePath "$env:GITHUB_WORKSPACE\rustdesk.exe" -ArgumentList "--config","$env:GITHUB_WORKSPACE\rustdesk-config"
          Start-Sleep -Seconds 10

      - name: Take Screenshot via PowerShell
        shell: pwsh
        run: |
          Add-Type -AssemblyName System.Windows.Forms
          Add-Type -AssemblyName System.Drawing
          $bounds = [System.Windows.Forms.Screen]::PrimaryScreen.Bounds
          $bitmap = New-Object System.Drawing.Bitmap $bounds.Width, $bounds.Height
          $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
          $graphics.CopyFromScreen($bounds.Location, [System.Drawing.Point]::Empty, $bounds.Size)
          $bitmap.Save("$env:GITHUB_WORKSPACE\screenshot.png", [System.Drawing.Imaging.ImageFormat]::Png)
          $graphics.Dispose()
          $bitmap.Dispose()

      - name: Upload Screenshot Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-screenshot
          path: screenshot.png

      - name: Upload RustDesk config for user modification
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-config
          path: rustdesk-config

      - name: Keep Runner Alive for 4 Hours
        shell: pwsh
        run: |
          Write-Host "Keeping the runner alive for 4 hours..."
          Start-Sleep -Seconds 14400  # 4 hours
